from setuptools import setup

setup(
    name='TrustButVerify',
    version='2.1.2',
    packages=['venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.progress',
              'venv.Lib.site-packages.pip._vendor.requests', 'venv.Lib.site-packages.pip._vendor.packaging',
              'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.index', 'venv.Lib.site-packages.pip._internal.utils',
              'venv.Lib.site-packages.pip._internal.models', 'venv.Lib.site-packages.pip._internal.network',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.pip._internal.operations.build',
              'venv.Lib.site-packages.pip._internal.operations.install',
              'venv.Lib.site-packages.pip._internal.distributions', 'venv.Lib.site-packages.adsi',
              'venv.Lib.site-packages.bits', 'venv.Lib.site-packages.mapi', 'venv.Lib.site-packages.odbc',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.isapi', 'venv.Lib.site-packages.shell',
              'venv.Lib.site-packages.timer', 'venv.Lib.site-packages.win32', 'venv.Lib.site-packages.win32.lz',
              'venv.Lib.site-packages.win32.ts', 'venv.Lib.site-packages.win32.api', 'venv.Lib.site-packages.win32.com',
              'venv.Lib.site-packages.win32.com.client', 'venv.Lib.site-packages.win32.com.gen_py',
              'venv.Lib.site-packages.win32.com.makegw', 'venv.Lib.site-packages.win32.com.server',
              'venv.Lib.site-packages.win32.com.servers', 'venv.Lib.site-packages.win32.com.storage',
              'venv.Lib.site-packages.win32.job', 'venv.Lib.site-packages.win32.net',
              'venv.Lib.site-packages.win32.pdh', 'venv.Lib.site-packages.win32.ras',
              'venv.Lib.site-packages.win32.file', 'venv.Lib.site-packages.win32.help',
              'venv.Lib.site-packages.win32.inet', 'venv.Lib.site-packages.win32.kras',
              'venv.Lib.site-packages.win32.mapi', 'venv.Lib.site-packages.win32.pipe',
              'venv.Lib.site-packages.win32.sspi', 'venv.Lib.site-packages.win32.wnet',
              'venv.Lib.site-packages.win32.event', 'venv.Lib.site-packages.win32.print',
              'venv.Lib.site-packages.win32.shell', 'venv.Lib.site-packages.win32.timer',
              'venv.Lib.site-packages.win32.trace', 'venv.Lib.site-packages.win32.console',
              'venv.Lib.site-packages.win32.perfmon', 'venv.Lib.site-packages.win32.process',
              'venv.Lib.site-packages.win32.profile', 'venv.Lib.site-packages.win32.propsys',
              'venv.Lib.site-packages.win32.service', 'venv.Lib.site-packages.win32.eventlog',
              'venv.Lib.site-packages.win32.internet', 'venv.Lib.site-packages.win32.security',
              'venv.Lib.site-packages.win32.clipboard', 'venv.Lib.site-packages.win32.distutils',
              'venv.Lib.site-packages.win32.sysloader', 'venv.Lib.site-packages.win32.credentials',
              'venv.Lib.site-packages.win32.directsound', 'venv.Lib.site-packages.win32.transaction',
              'venv.Lib.site-packages.win32.cryptography', 'venv.Lib.site-packages.win32.authorization',
              'venv.Lib.site-packages.win32.taskscheduler', 'venv.Lib.site-packages.win32.servicemanager',
              'venv.Lib.site-packages.autopy', 'venv.Lib.site-packages.pynput', 'venv.Lib.site-packages.pynput._util',
              'venv.Lib.site-packages.pynput.mouse', 'venv.Lib.site-packages.pynput.keyboard',
              'venv.Lib.site-packages.axdebug', 'venv.Lib.site-packages.ifilter', 'venv.Lib.site-packages.netbios',
              'venv.Lib.site-packages.perfmon', 'venv.Lib.site-packages.propsys', 'venv.Lib.site-packages.win32lz',
              'venv.Lib.site-packages.win32ts', 'venv.Lib.site-packages.adodbapi', 'venv.Lib.site-packages.axscript',
              'venv.Lib.site-packages.dateutil', 'venv.Lib.site-packages.dateutil.tz',
              'venv.Lib.site-packages.dateutil.parser', 'venv.Lib.site-packages.dateutil.zoneinfo',
              'venv.Lib.site-packages.exchange', 'venv.Lib.site-packages.internet', 'venv.Lib.site-packages.mmapfile',
              'venv.Lib.site-packages.win2kras', 'venv.Lib.site-packages.win32api', 'venv.Lib.site-packages.win32com',
              'venv.Lib.site-packages.win32com.test', 'venv.Lib.site-packages.win32com.demos',
              'venv.Lib.site-packages.win32com.shell', 'venv.Lib.site-packages.win32com.client',
              'venv.Lib.site-packages.win32com.makegw', 'venv.Lib.site-packages.win32com.server',
              'venv.Lib.site-packages.win32com.servers', 'venv.Lib.site-packages.win32com.axscript',
              'venv.Lib.site-packages.win32com.authorization', 'venv.Lib.site-packages.win32con',
              'venv.Lib.site-packages.win32ext', 'venv.Lib.site-packages.win32job', 'venv.Lib.site-packages.win32net',
              'venv.Lib.site-packages.win32pdh', 'venv.Lib.site-packages.win32ras', 'venv.Lib.site-packages.winerror',
              'venv.Lib.site-packages.axcontrol', 'venv.Lib.site-packages.backports',
              'venv.Lib.site-packages.backports.configparser', 'venv.Lib.site-packages.dateutils',
              'venv.Lib.site-packages.pythoncom', 'venv.Lib.site-packages.pythonwin.pywin',
              'venv.Lib.site-packages.pythonwin.pywin.mfc', 'venv.Lib.site-packages.pythonwin.pywin.idle',
              'venv.Lib.site-packages.pythonwin.pywin.Demos.ocx', 'venv.Lib.site-packages.pythonwin.pywin.tools',
              'venv.Lib.site-packages.pythonwin.pywin.dialogs', 'venv.Lib.site-packages.pythonwin.pywin.docking',
              'venv.Lib.site-packages.pythonwin.pywin.debugger', 'venv.Lib.site-packages.pythonwin.pywin.framework',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor.color',
              'venv.Lib.site-packages.pythonwin.pywin.scintilla', 'venv.Lib.site-packages.win32auth',
              'venv.Lib.site-packages.win32cred', 'venv.Lib.site-packages.win32file',
              'venv.Lib.site-packages.win32help', 'venv.Lib.site-packages.win32inet',
              'venv.Lib.site-packages.win32kras', 'venv.Lib.site-packages.win32pipe',
              'venv.Lib.site-packages.win32wnet', 'venv.Lib.site-packages.pywintypes',
              'venv.Lib.site-packages.win32crypt', 'venv.Lib.site-packages.win32event',
              'venv.Lib.site-packages.win32print', 'venv.Lib.site-packages.win32shell',
              'venv.Lib.site-packages.win32sound', 'venv.Lib.site-packages.win32timer',
              'venv.Lib.site-packages.win32trace', 'venv.Lib.site-packages.directsound',
              'venv.Lib.site-packages.win32comext.adsi', 'venv.Lib.site-packages.win32comext.bits',
              'venv.Lib.site-packages.win32comext.mapi', 'venv.Lib.site-packages.win32comext.shell',
              'venv.Lib.site-packages.win32comext.axdebug', 'venv.Lib.site-packages.win32comext.ifilter',
              'venv.Lib.site-packages.win32comext.propsys', 'venv.Lib.site-packages.win32comext.axscript',
              'venv.Lib.site-packages.win32comext.axscript.client',
              'venv.Lib.site-packages.win32comext.axscript.server', 'venv.Lib.site-packages.win32comext.internet',
              'venv.Lib.site-packages.win32comext.axcontrol', 'venv.Lib.site-packages.win32comext.directsound',
              'venv.Lib.site-packages.win32comext.directsound.test', 'venv.Lib.site-packages.win32comext.authorization',
              'venv.Lib.site-packages.win32comext.taskscheduler', 'venv.Lib.site-packages.win32evtlog',
              'venv.Lib.site-packages.win32svcmgr', 'venv.Lib.site-packages.win32console',
              'venv.Lib.site-packages.win32inetcon', 'venv.Lib.site-packages.win32process',
              'venv.Lib.site-packages.win32profile', 'venv.Lib.site-packages.win32propsys',
              'venv.Lib.site-packages.win32service', 'venv.Lib.site-packages.authorization',
              'venv.Lib.site-packages.ntsecuritycon', 'venv.Lib.site-packages.taskscheduler',
              'venv.Lib.site-packages.win32internet', 'venv.Lib.site-packages.win32rcparser',
              'venv.Lib.site-packages.win32security', 'venv.Lib.site-packages.win32timezone',
              'venv.Lib.site-packages.servicemanager', 'venv.Lib.site-packages.win32clipboard',
              'venv.Lib.site-packages.win32scheduler', 'venv.Lib.site-packages.win32gui_struct',
              'venv.Lib.site-packages.pywin32_testutil', 'venv.Lib.site-packages.win32transaction',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='JRytting',
    author_email='',
    description=''
)
